scrum_board/board/urls.py
from django.urls import path

from . import views

app_name = 'board'

urlpatterns = [
    path(
        '',
        views.BoardsListView.as_view(),
        name='boards',
    ),
    path(
        '<int:pk>/',
        views.BoardDetailView.as_view(),
        name='tasks',
    ),

    path(
        '<int:pk>/create_task/',
        views.TaskCreateView.as_view(
            extra_context={'title': 'Создание задачи'}
        ),
        name='create_task'
    ),
    path(
        'create_board/',
        views.BoardCreateView.as_view(),
        name='create_board'
    ),
    path(
        '<int:board_id>/<int:task_id>/next',
        views.next,
        name='next_state',
    ),
    path(
        '<int:board_id>/<int:task_id>/last',
        views.last,
        name='last_state',
    ),
    path(
        '<int:board_id>/<int:task_id>/delete',
        views.delete,
        name='delete_task',
    )
]

scrum_board/scrum_board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls'), name='homepage'),
    path('feedback/', include('feedback.urls'), name='feedback'),
    path('boards/', include('board.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

scrum_board/board/models.py
from django.db import models

from .managers import BoardManager, TaskManager
from users.models import CustomUser


class Task(models.Model):
    """
    The task that the user has set. Has a executor, creator,
    text, timeline and status.
    """
    objects = TaskManager
    STATUS_CHOICES = (
        ('Бклг', 'Бэклог'),
        ('Сдлть', 'Сделать'),
        ('Впрцсс', 'В процессе'),
        ('Тстртс', 'Тестируется'),
        ('Гтв', 'Готово'),
    )
    creator = models.ForeignKey(
        CustomUser,
        verbose_name='создатель',
        on_delete=models.CASCADE,
        help_text='Создатель задачи.',
        related_name='creator_tasks',
    )

    executor = models.ForeignKey(
        CustomUser,
        verbose_name='исполнитель',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text='Исполнитель задачи.',
        related_name='executor_tasks',
    )

    text = models.TextField(
        verbose_name='текст',
        help_text='Текст задачи.',
    )

    start_date = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name='начало',
        help_text='Дата начала выполнения задачи.',
    )

    end_date = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name='конец',
        help_text='Дата дедлайна.',
    )

    status = models.CharField(
        choices=STATUS_CHOICES,
        max_length=20,
        verbose_name='состояние',
        help_text='Состояние задачи.',
    )

    class Meta:
        verbose_name = 'задача'
        verbose_name_plural = 'задачи'

    def __str__(self):
        return self.text


class Board(models.Model):
    """
    A board where tasks of several users are stored
    """
    objects = BoardManager()
    name = models.CharField(
        max_length=30,
        verbose_name='название',
        help_text='Название доски.',
    )
    creator = models.ForeignKey(
        CustomUser,
        verbose_name='создатель',
        on_delete=models.CASCADE,
        help_text='Создатель доски.',
        related_name='creator_board',
    )
    executors = models.ManyToManyField(
        CustomUser,
        verbose_name='исполнители',
        help_text='Участники доски.',
    )

    tasks = models.ManyToManyField(
        Task,
        verbose_name='задачи',
        help_text='Задачи определенной доски.',
    )

    class Meta:
        verbose_name = 'доска'
        verbose_name_plural = 'доски'

    def __str__(self):
        return f'Доска {self.name} #{self.pk}'

scrum_board/board/forms.py
from django import forms

from .models import Task, Board
from core.forms import BaseForm


class TaskForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Task
        exclude = (
            Task.creator.field.name,
        )


class BoardCreateForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Board
        exclude = (
            Board.name,
        )
        fields = ('name', 'executors', )

scrum_board/board/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from .forms import TaskForm, BoardCreateForm
from .models import Board, Task


class BoardsListView(UserPassesTestMixin, generic.ListView):
    """
    List of all boards for a specific user
    render
    """
    model = Board
    template_name = 'board/list.html'

    def test_func(self):
        return (self.request.user.is_authenticated
                and self.request.user.is_active)

    login_url = reverse_lazy('users:login')

    def get_context_data(self):
        context = super().get_context_data()

        user = self.request.user
        context['title'] = 'Доски'
        context['boards'] = Board.objects.user_boards(user)
        return context


class BoardDetailView(UserPassesTestMixin, generic.DetailView):
    """
    View class for display scrum board
    render board/board.html
    """
    model = Board
    template_name = 'board/board.html'

    def test_func(self):
        return (self.request.user.is_authenticated
                and self.request.user.is_active)

    login_url = reverse_lazy('users:login')

    def get_object(self):
        return get_object_or_404(
            Board,
            pk=self.kwargs['pk'],
        )

    def get_context_data(self, **kwargs):
        """
        :return: context with item
        """
        context = super().get_context_data()
        board = self.get_object()
        context['board'] = board.pk
        context['title'] = 'Подробнее'
        context['board'] = board.pk
        tasks = board.tasks.all()
        context['backlog'] = tasks.filter(
            status='Бэклог'
        )
        context['todo'] = tasks.filter(
            status='Сделать'
        )
        context['progress'] = tasks.filter(
            status='В процессе'
        )
        context['test'] = tasks.filter(
            status='Тестируется'
        )
        context['done'] = tasks.filter(
            status='Готово'
        )
        return context


class TaskCreateView(UserPassesTestMixin, generic.FormView):
    """Form for creating a task"""
    template_name = 'board/create_task.html'
    form_class = TaskForm

    def test_func(self):
        return (self.request.user.is_authenticated
                and self.request.user.is_active)

    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        task = Task.objects.create(
            creator=self.request.user,
            **form.cleaned_data
        )
        Board.objects.get(pk=self.kwargs['pk']).tasks.add(task)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('board:tasks', kwargs={'pk': self.kwargs['pk']})


class BoardCreateView(UserPassesTestMixin, generic.FormView):
    """Form for creating Board"""
    template_name = 'board/create_board.html'
    form_class = BoardCreateForm
    success_url = reverse_lazy('homepage:home')

    def test_func(self):
        return (self.request.user.is_authenticated
                and self.request.user.is_active)

    login_url = reverse_lazy('users:login')

    def get_context_data(self, **kwargs):
        """
        :return: context with title
        """
        context = super().get_context_data()
        context['title'] = 'Создание доски'
        return context

    def form_valid(self, form):
        board = form.save(commit=False)
        board.creator = self.request.user
        board.save()
        form.save_m2m()
        return super(BoardCreateView, self).form_valid(form)


def next(requests, board_id, task_id):
    item = Task.objects.get(pk=task_id)
    if item.status == 'Бэклог':
        item.status = 'Сделать'
    elif item.status == 'Сделать':
        item.status = 'В процессе'
    elif item.status == 'В процессе':
        item.status = 'Тестируется'
    elif item.status == 'Тестируется':
        item.status = 'Готово'
    item.save()
    return redirect('board:tasks', pk=board_id)


def last(requests, board_id, task_id):
    item = Task.objects.get(pk=task_id)
    if item.status == 'Готово':
        item.status = 'Тестируется'
    elif item.status == 'Тестируется':
        item.status = 'В процессе'
    elif item.status == 'В процессе':
        item.status = 'Сделать'
    elif item.status == 'Сделать':
        item.status = 'Бэклог'
    item.save()
    return redirect('board:tasks', pk=board_id)


def delete(requests, board_id, task_id):
    item = Task.objects.get(pk=task_id)
    item.delete()
    return redirect('board:tasks', pk=board_id)

scrum_board/templates/board/board.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <a type="button" class="btn btn-success btn-lg" href="{% url 'board:create_task' board %}">Создать задачу</a>
    <div class='row'>
        <div class="backlog col-2">
            <div class="font-weight-bold">
                Бэклог
            </div>
            {% for task in backlog %}
                {% include "includes/task.html" %}
            {% endfor %}
        </div>
        <div class="todo col-2">
            <div class="font-weight-bold">
                Сделать
            </div>
            {% for task in todo %}
                {% include "includes/task.html" %}
            {% endfor %}
        </div>
        <div class="progress_task col-2">
            <div class="font-weight-bold">
                В процессе
            </div>
            {% for task in progress %}
                {% include "includes/task.html" %}
            {% endfor %}
        </div>
        <div class="test col-2">
            <div class="font-weight-bold">
                Тестируется
            </div>
            {% for task in test %}
                {% include "includes/task.html" %}
            {% endfor %}
        </div>
        <div class="done col-2">
            <div class="font-weight-bold">
                Готово
            </div>
            {% for task in done %}
                {% include "includes/task.html" %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

scrum_board/templates/board/create_board.html
{% extends 'base.html' %}

{% block content %}
    <h2>Создание доски</h2>
    <form method="post">
        {% csrf_token %}
        <label for="{{ form.name.id_for_label }}"></label>
        <input type="text" class="form-control"
               maxlength="30" name="{{ form.name.name }}"
               placeholder="{{ form.name.help_text }}" id="{{ form.name.id_for_label }}" required>
        <br>
        {{ form.executors }}
        <br>
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
{% endblock %}

scrum_board/templates/board/create_task.html
{% extends 'base.html' %}

{% block content %}
    <h2>Создание задачи</h2>
    {% include 'includes/form.html' %}
{% endblock %}

scrum_board/templates/board/list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <a type="button" class="btn btn-success btn-lg" href="{% url 'board:create_board' %}">Создать доску</a>
    <br>
    <br>
    {% include "includes/list.html" %}
{% endblock %}