scrum_board/board/urls.py
from django.urls import path

from . import views

app_name = 'board'

urlpatterns = [
    path(
        '',
        views.BoardsListView.as_view(),
        name='boards',
    ),
    path(
        '<int:pk>/',
        views.BoardDetailView.as_view(),
        name='tasks',
    ),

    path(
        '<int:pk>/create_task/',
        views.TaskCreateView.as_view(
            extra_context={'title': 'Создание задачи'}
        ),
        name='create_task'
    ),
    path(
        'create_board/',
        views.BoardCreateView.as_view(),
        name='create_board'
    ),
    path(
        '<int:board_id>/<int:task_id>/next',
        views.next,
        name='next_state',
    ),
    path(
        '<int:board_id>/<int:task_id>/last',
        views.last,
        name='last_state',
    ),
    path(
        '<int:board_id>/<int:task_id>/delete',
        views.delete,
        name='delete_task',
    )
]

scrum_board/scrum_board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls'), name='homepage'),
    path('feedback/', include('feedback.urls'), name='feedback'),
    path('boards/', include('board.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

scrum_board/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'login/',
        views.LoginView.as_view(),
        name='login',
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='logout',
    ),
    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(),
        name='password_change_done',
    ),
    path(
        'password_change/',
        views.PasswordChangeView.as_view(),
        name='password_change',
    ),
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'password_reset/compliete/',
        views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(),
        name='password_reset',
    ),
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        'profile/<int:pk>/edit/',
        views.ProfileEditView.as_view(),
        name='profile_edit',
    ),
    path(
        'profile/<int:pk>/',
        views.ProfileView.as_view(),
        name='profile',
    ),
]

scrum_board/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    """Custom user model with additional unique email field."""
    email = models.EmailField(
        'email',
        unique=True,
        help_text='Ваш email',
    )

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def __str__(self):
        return self.username

scrum_board/users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser
from core.forms import BaseForm


class CustomUserCreationForm(UserCreationForm):
    """Custom form for creating new user."""

    class Meta(UserCreationForm):
        model = CustomUser
        fields = (
            CustomUser.username.field.name,
            CustomUser.email.field.name,
        )


class CustomUserChangeForm(BaseForm, UserChangeForm):
    password = None

    class Meta:
        model = CustomUser
        fields = (
            CustomUser.first_name.field.name,
            CustomUser.last_name.field.name,
        )

scrum_board/users/views.py
from django.contrib.auth import views
from django.urls import reverse_lazy
from django.views import generic

from .forms import CustomUserChangeForm, CustomUserCreationForm
from .models import CustomUser


class LoginView(views.LoginView):
    """View class for login page.

    render login html.
    """
    template_name = 'users/login.html'
    success_url = reverse_lazy('homepage:home')

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['title'] = 'Вход'
        context['btn_label'] = 'Войти'
        return context


class LogoutView(views.LogoutView):
    """View class for logout page.

    render logout html.
    """
    template_name = 'users/logout.html'

    def get_context_data(self, **kwargs):
        context = super(
            LogoutView,
            self,
        ).get_context_data(**kwargs)
        context['title'] = 'Выход'
        context['message'] = 'Вы успешно вышли!'
        context['btn_label'] = 'На главную'
        return context


class PasswordChangeDoneView(views.PasswordChangeDoneView):
    """View class for password change done page.

    render password change done html.
    """
    template_name = 'users/password_change_done.html'

    def get_context_data(self, **kwargs):
        context = super(
            PasswordChangeDoneView,
            self,
        ).get_context_data(**kwargs)
        context['title'] = 'Смена пароля'
        context['message'] = 'Вы успешно сменили пароль!'
        context['btn_label'] = 'На главную'
        return context


class PasswordChangeView(views.PasswordChangeView):
    """View class for password change page.

    render password change html.
    """
    template_name = 'users/password_change.html'
    success_url = reverse_lazy('users:password_change_done')

    def get_context_data(self, **kwargs):
        context = super(
            PasswordChangeView,
            self,
        ).get_context_data(**kwargs)
        context['title'] = 'Смена пароля'
        context['btn_label'] = 'Поменять'
        return context


class PasswordResetDoneView(views.PasswordResetDoneView):
    """View class for password reset done page.

    render password reset done html.
    """
    template_name = 'users/password_reset_done.html'

    def get_context_data(self, **kwargs):
        context = super(
            PasswordResetDoneView,
            self,
        ).get_context_data(**kwargs)
        context['title'] = 'Сброс пароля'
        context['message'] = 'Вам на почту отправлено письмо с подтверждением'
        context['btn_label'] = 'На главную'
        return context


class PasswordResetConfirmView(views.PasswordResetConfirmView):
    """View class for password reset confirm page.

    render password reset confirm html.
    """
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')

    def get_context_data(self, **kwargs):
        context = super(
            PasswordResetConfirmView,
            self,
        ).get_context_data(**kwargs)
        context['title'] = 'Сброс пароля'
        context['btn_label'] = 'Сбросить'
        return context


class PasswordResetCompleteView(views.PasswordResetCompleteView):
    """View class for password reset complete page.

    render password reset complete html.
    """
    template_name = 'users/password_reset_complete.html'

    def get_context_data(self, **kwargs):
        context = super(
            PasswordResetCompleteView,
            self,
        ).get_context_data(**kwargs)
        context['title'] = 'Сброс пароля'
        context['message'] = 'Пароль успешно сброшен'
        context['btn_label'] = 'На главную'
        return context


class PasswordResetView(views.PasswordResetView):
    """View class for password reset page.

    render password reset html.
    """
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')

    def get_context_data(self, **kwargs):
        context = super(
            PasswordResetView,
            self,
        ).get_context_data(**kwargs)
        context['title'] = 'Сброс пароля'
        context['btn_label'] = 'Сбросить'
        return context


class SignUpView(generic.edit.CreateView):
    """View class for signup page.

    render signup html.
    """
    template_name = 'users/signup.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')

    def get_context_data(self, **kwargs):
        context = super(
            SignUpView,
            self,
        ).get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        context['btn_label'] = 'Подтвердить'
        return context


class ProfileEditView(generic.edit.UpdateView):
    """View class for profile edit page.

    render profile edit html.
    """
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('homepage:home')

    def get_context_data(self, **kwargs):
        context = super(
            ProfileEditView,
            self,
        ).get_context_data(**kwargs)
        context['title'] = 'Ваш профиль'
        return context


class ProfileView(generic.edit.UpdateView):
    """View class for profile page.

    render profile html.
    """
    model = CustomUser
    fields = ('first_name', 'last_name', 'email',)
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super(
            ProfileView,
            self,
        ).get_context_data(**kwargs)
        context['title'] = 'Ваш профиль'
        return context

scrum_board/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    {% include "includes/fields.html" %}
    <a href={% url 'users:password_reset' %}>Забыли пароль?</a>
    <a href={% url 'users:signup' %}>Зарегестрироваться</a>
{% endblock content %}

scrum_board/templates/users/logout.html
{% extends 'base.html' %}

{% block content %}
    {% include "includes/success.html" %}
{% endblock content %}

scrum_board/templates/users/password_change.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        {% include "includes/fields.html" %}
    {% else %}
        <h3>Вам менять нечего, аноним!</h3>
    {% endif %}
{% endblock content %}

scrum_board/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
    {% include "includes/success.html" %}
{% endblock content %}

scrum_board/templates/users/password_reset.html
{% extends 'base.html' %}

{% block content %}
    {% include "includes/fields.html" %}
{% endblock content %}

scrum_board/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    {% include "includes/success.html" %}
{% endblock content %}

scrum_board/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    {% include "includes/fields.html" %}
{% endblock content %}

scrum_board/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
    {% include "includes/success.html" %}
{% endblock content %}

scrum_board/templates/users/password_reset_email.html
{% autoescape off %}
    To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
    click the link below:

    {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

    If clicking the link above doesn't work, please copy and paste the URL in a new browser
    window instead.

    Sincerely,
    The Developer
{% endautoescape %}

scrum_board/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>Профиль</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                <div class="row g-3 align-items-center">
                    <div class="col-auto">
                        {{ field }}
                    </div>
                    <div class="col-auto">
                        {{ field.label_tag }}
                    </div>
                    <div class="col-auto">
                        {% if field.help_text %}
                            <span class="form-text">
                                {{ field.help_text }}
                            </span>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <a class='btn btn-warning' href={% url 'users:password_change' %}>Поменять пароль</a>
        <input class='btn btn-success' type="submit" value="Изменить" />
    </form>
    <a style='margin-top:20px'  class='btn btn-danger' type="" href={% url 'users:logout' %}>Выход</a>
{% endblock content %}

scrum_board/templates/users/signup.html
{% extends 'base.html' %}

{% block content %}
    {% include "includes/fields.html" %}
{% endblock content %}