scrum_board/board/urls.py
from django.urls import path

from . import views

app_name = 'board'

urlpatterns = [
    path(
        '',
        views.BoardsListView.as_view(),
        name='boards',
    ),
    path(
        '<int:pk>/',
        views.BoardDetailView.as_view(),
        name='tasks',
    ),

    path(
        '<int:pk>/create_task/',
        views.TaskCreateView.as_view(
            extra_context={'title': 'Создание задачи'}
        ),
        name='create_task'
    ),
    path(
        'create_board/',
        views.BoardCreateView.as_view(),
        name='create_board'
    ),
    path(
        '<int:board_id>/<int:task_id>/next',
        views.next,
        name='next_state',
    ),
    path(
        '<int:board_id>/<int:task_id>/last',
        views.last,
        name='last_state',
    ),
    path(
        '<int:board_id>/<int:task_id>/delete',
        views.delete,
        name='delete_task',
    )
]

scrum_board/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

scrum_board/scrum_board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls'), name='homepage'),
    path('feedback/', include('feedback.urls'), name='feedback'),
    path('boards/', include('board.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

scrum_board/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'login/',
        views.LoginView.as_view(),
        name='login',
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='logout',
    ),
    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(),
        name='password_change_done',
    ),
    path(
        'password_change/',
        views.PasswordChangeView.as_view(),
        name='password_change',
    ),
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'password_reset/compliete/',
        views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(),
        name='password_reset',
    ),
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        'profile/<int:pk>/edit/',
        views.ProfileEditView.as_view(),
        name='profile_edit',
    ),
    path(
        'profile/<int:pk>/',
        views.ProfileView.as_view(),
        name='profile',
    ),
]

scrum_board/templates/includes/card.html
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Задание для {{ task.executor }}</h5>
      <p class="card-text">{{ task.text }}</p>
      <a href="#" class="btn btn-primary col-5" style="font-size:11px;">Назад</a>
      <a href="#" class="btn btn-primary col-5" style="font-size:11px;">Дальше</a>
    </div>
</div>

scrum_board/templates/includes/fields.html
<form method="post">
    {% csrf_token %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error|escape }}
            </div>
        {% endfor %}
    {% endif %}
    {% for field in form %}
        <div class="mb-3">
            <div class="row g-3 align-items-center">
                <div class="col-auto ">
                    {{ field }}
                </div>
                <div class="col-auto">
                    {{ field.label_tag }}
                </div>
                <div class="col-auto">
                    {% if field.help_text %}
                        <span class="form-text">
                            {{ field.help_text }}
                        </span>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">{{ btn_label }}</button>
</form>

scrum_board/templates/includes/footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top align-bottom">
    <div class="container">
        <p class="col-md-4 mb-0 text-muted">©{% now "Y" %} Григорий Логин, Андрей Харин, Сергей Иожица. Все права защищены</p>
        <ul class="nav col-md-4 justify-content-start">
            <li class="nav-item"><a href="{% url 'feedback' %}" class="nav-link px-2 text-muted">Обратная связь</a></li>
        </ul>
    </div>
</footer>

scrum_board/templates/includes/form.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ error | escape }}
            </div>
        {% endfor %}
    {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error | escape }}
            </div>
        {% endfor %}
{% endif %}
<br>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div>
            {{ field.label_tag }}{{ field }}
            {% if field.help_text %}
                <p class="help">{{ field.help_text | safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    {% for field in profile_form %}
        <div>
            {{ field.label_tag }} {{ field }}
            {% if field.help_text %}
                <p class="help">{{ field.help_text | safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <br>
    <input class="btn btn-primary" type="submit" value="Подтвердить">
</form>

scrum_board/templates/includes/header.html
{% load static %}

<header>
    <nav class="navbar navbar-expand-lg bg-light">
        {% with request.resolver_match.view_name as view_name %}
            <div class="container">
                <nav class="nav nav-pills nav-justified">
                    <a class="navbar-brand" href="{% url 'homepage:home' %}">
                        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top"
                             alt="">
                        To Do
                    </a>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="{% if view_name == 'board:boards' %}btn btn-success{% else %}nav-link{% endif %}"
                               href="{% url 'board:boards' %}">Доски</a>
                        </li>
                        <a class="{% if view_name == 'board:create_board' %}btn btn-success{% else %}nav-link{% endif %}"
                           href="{% url 'board:create_board' %}">Создать доску</a>
                    </ul>
                </nav>
                <nav class="nav nav-pills nav-justified">
                    {% if user and user.is_authenticated %}
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ request.user.username }}
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:profile' user.pk %}">Мой профиль</a>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <a class="{% if view_name == 'users:login' %}nav-item nav-link active {% else %} nav-item nav-link {% endif %}"
                           href="{% url 'users:login' %}">Вход</a>
                        <a class="{% if view_name == 'users:signup' %}nav-item nav-link active {% else %} nav-item nav-link {% endif %}"
                           href="{% url 'users:signup' %}">Регистрация</a>
                    {% endif %}
                </nav>
            </div>
        {% endwith %}
    </nav>
</header>

scrum_board/templates/includes/list.html
<div class="cells">
    {% for board in boards %}
    <div class="card">
        <div class="card-header">
            <h4>{{ board.name }}</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title">Доска {{ board.creator }}</h5>
            <p class="card-text">Участники:
                {% for user in board.executors.all %}
                    {{ user.username }},
                {% endfor %}
            </p>
            <a href="{% url 'board:tasks' board.pk %}" class="btn btn-success">
                Посмотреть
            </a>
        </div>
    </div>
    {% endfor %}
</div>

scrum_board/templates/includes/success.html
<h3>{{ message }}</h3>
<a class='btn btn-success' href={% url 'homepage:home' %}>{{ btn_label }}</a>

scrum_board/templates/includes/task.html
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Задание для {{ task.executor }}</h5>

      <p class="card-text">{{ task.text }}</p>
      <a href="{% url 'board:last_state' board task.pk %}" class="btn btn-primary col-5" style="font-size:11px;">Назад</a>
      <a href="{% url 'board:next_state' board task.pk %}" class="btn btn-primary col-5" style="font-size:11px;">Дальше</a>

      {% if user == task.creator %}
        <a href="{% url 'board:delete_task' board task.pk %}" class="btn btn-danger" style="font-size:11px; margin-top:10px;">Удалить</a>
      {% endif %}
    </div>
</div>